from __future__ import annotations

import argparse
import getpass
import json
import logging
import signal
import sys
import threading
from datetime import datetime, timedelta
from pathlib import Path

from . import __version__
from .auth import hash_password
from .ai_analyzer import probe_deepseek
from .config import Settings, load_dotenv
from .database import Database
from .mail import Mailer
from .provider import build_provider
from .scheduler import due_recommendation_slot, seconds_until_next_event, slot_job_name
from .service import JobOutcome, ScoreFourfoldService
from .web import DashboardApplication, DashboardServer


LOGGER = logging.getLogger("score_fourfold")


def _parse_now(raw: str | None, settings: Settings) -> datetime:
    if not raw:
        return datetime.now(settings.timezone)
    parsed = datetime.fromisoformat(raw.replace("Z", "+00:00"))
    if parsed.tzinfo is None:
        return parsed.replace(tzinfo=settings.timezone)
    return parsed.astimezone(settings.timezone)


def _build_service(settings: Settings) -> ScoreFourfoldService:
    database = Database(settings.database_path)
    database.initialize()
    return ScoreFourfoldService(settings, database, build_provider(settings), Mailer(settings))


def _run_recorded(service: ScoreFourfoldService, job_name: str, now: datetime, action) -> JobOutcome:
    started_at = datetime.now(service.settings.timezone)
    try:
        outcome = action(now)
    except Exception as exc:
        finished_at = datetime.now(service.settings.timezone)
        service.database.record_job(job_name, started_at, finished_at, "error", f"{type(exc).__name__}: {exc}")
        service.enqueue_error(job_name, exc, finished_at)
        raise
    finished_at = datetime.now(service.settings.timezone)
    service.database.record_job(job_name, started_at, finished_at, outcome.status, outcome.detail)
    return outcome


def _run_cycle(
    service: ScoreFourfoldService,
    now: datetime,
    *,
    include_recommend: bool = True,
    recommend_job_name: str = "recommend",
    include_finalize: bool = False,
    finalize_job_name: str = "recommend-finalize",
) -> tuple[list[JobOutcome], list[str]]:
    outcomes: list[JobOutcome] = []
    errors: list[str] = []
    actions = [("settle", service.settle)]
    if include_finalize:
        actions.insert(0, (finalize_job_name, service.finalize_recommendation_day))
    if include_recommend:
        actions.insert(0, (recommend_job_name, service.recommend))
    for name, action in actions:
        try:
            outcome = _run_recorded(service, name, now, action)
        except Exception as exc:
            error = f"{name}: {type(exc).__name__}: {exc}"
            LOGGER.exception("%s failed", name)
            errors.append(error)
        else:
            outcomes.append(outcome)
            LOGGER.info("%s: %s", name, outcome.detail)
    # Send recommendation, settlement and error notifications queued in this cycle.
    try:
        outcome = _run_recorded(service, "send-mail", now, service.send_mail)
    except Exception as exc:
        error = f"send-mail: {type(exc).__name__}: {exc}"
        LOGGER.exception("send-mail failed")
        errors.append(error)
    else:
        outcomes.append(outcome)
        LOGGER.info("send-mail: %s", outcome.detail)
    return outcomes, errors


def _build_manual_trigger(
    service: ScoreFourfoldService,
    wake_event: threading.Event,
):
    """Build an idempotent dashboard action using the normal recommendation path."""

    def trigger(request_id: str) -> tuple[str, str]:
        started_at = service.now()
        if not service.database.claim_web_request(request_id, started_at):
            previous = service.database.get_web_request(request_id)
            if previous is None:
                return "cooldown", "手动操作间隔至少5分钟，请稍后再试"
            if previous[0] == "running":
                return "busy", "本次手动推荐正在执行，请稍后刷新页面查看结果"
            return previous

        status = "error"
        detail = "手动推荐执行异常，错误通知已进入邮件队列"
        try:
            outcome = _run_recorded(
                service,
                f"manual-recommend:{request_id}",
                started_at,
                service.try_recommend,
            )
        except Exception:
            LOGGER.exception("manual recommendation failed")
        else:
            status, detail = outcome.status, outcome.detail

        finished_at = service.now()
        service.database.finish_web_request(request_id, status, detail, finished_at)

        # A manual attempt replaces the latest due scheduled attempt. Recording
        # the slot prevents an immediate second provider request when the daemon
        # wakes to deliver mail generated by this action.
        if status != "busy":
            slot = due_recommendation_slot(
                started_at,
                service.settings.recommendation_times,
                service.settings.recommendation_latest_start,
                service.database.has_job_run,
            )
            if slot is not None:
                service.database.record_job(
                    slot_job_name(started_at, slot),
                    started_at,
                    finished_at,
                    f"manual-{status}",
                    detail,
                )
            wake_event.set()
        return status, detail

    return trigger


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="score-fourfold",
        description="竞彩足球明确比分4串1的2元基准推荐与自动结算服务",
    )
    parser.add_argument("--env-file", default=".env", help="dotenv配置文件，默认 .env")
    parser.add_argument("--verbose", action="store_true", help="输出调试日志")
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("init-db", help="初始化SQLite数据库")
    subparsers.add_parser("check-config", help="检查配置（不会显示邮箱授权码）")
    subparsers.add_parser("status", help="显示计划、收益和邮件状态")
    subparsers.add_parser("health", help="检查配置和邮件死信，供容器健康检查使用")

    password_hash = subparsers.add_parser(
        "hash-password", help="生成网页登录密码哈希（不会保存或显示明文密码）"
    )
    password_hash.add_argument(
        "--stdin",
        action="store_true",
        help="从标准输入读取一行密码，供升级脚本生成随机密码",
    )

    probe = subparsers.add_parser("probe-data", help="只读探测赔率和最近赛果接口")
    probe.add_argument("--now", help="测试用时间")
    subparsers.add_parser("probe-ai", help="用最小请求检查DeepSeek配置和连通性")

    recommend = subparsers.add_parser("recommend", help="立即尝试生成一张推荐计划")
    recommend.add_argument("--now", help="测试用时间，例如 2026-07-14T12:00:00+08:00")

    settle = subparsers.add_parser("settle", help="立即检查并结算待结算计划")
    settle.add_argument("--now", help="测试用时间")

    send_mail = subparsers.add_parser("send-mail", help="发送邮件发件箱中的待发邮件")
    send_mail.add_argument("--now", help="测试用时间")

    test_mail = subparsers.add_parser("test-mail", help="发送一封不计入账本的配置测试邮件")
    test_mail.add_argument("--now", help="测试用时间")

    run_cycle = subparsers.add_parser("run-cycle", help="依次执行推荐、结算和邮件发送")
    run_cycle.add_argument("--now", help="测试用时间")

    daemon = subparsers.add_parser("daemon", help="常驻运行，按配置间隔执行完整周期")
    daemon.add_argument("--once", action="store_true", help="只执行一次，便于容器/cron调用")
    return parser


def _safe_settings(settings: Settings) -> dict[str, object]:
    return {
        "data_provider": settings.data_provider,
        "sporttery_odds_url": settings.sporttery_odds_url,
        "sporttery_results_url": settings.sporttery_results_url,
        "okooo_base_url": settings.okooo_base_url,
        "json_data_file": str(settings.json_data_file),
        "timezone": settings.timezone_name,
        "database_path": str(settings.database_path),
        "mail_to": settings.mail_to,
        "smtp_host": settings.smtp_host,
        "smtp_port": settings.smtp_port,
        "smtp_username_configured": bool(settings.smtp_username),
        "smtp_auth_code_configured": bool(settings.smtp_auth_code),
        "mail_dry_run": settings.mail_dry_run,
        "min_lead_minutes": settings.min_lead_minutes,
        "max_lookahead_hours": settings.max_lookahead_hours,
        "min_score_probability": settings.min_score_probability,
        "min_joint_probability": settings.min_joint_probability,
        "had_enabled": settings.had_enabled,
        "had_pass_sizes": list(settings.had_pass_sizes),
        "min_had_probability": settings.min_had_probability,
        "min_had_joint_probability": settings.min_had_joint_probability,
        "max_plans_per_business_date": settings.max_plans_per_business_date,
        "poll_interval_seconds": settings.poll_interval_seconds,
        "recommendation_times": [value.strftime("%H:%M") for value in settings.recommendation_times],
        "recommendation_latest_start": settings.recommendation_latest_start.strftime("%H:%M"),
        "recommendation_deadline": settings.recommendation_deadline.strftime("%H:%M"),
        "recommendation_mail_cutoff": (
            datetime.combine(datetime.now(settings.timezone).date(), settings.recommendation_deadline)
            - timedelta(minutes=settings.recommendation_send_buffer_minutes)
        ).strftime("%H:%M"),
        "result_check_delay_minutes": settings.result_check_delay_minutes,
        "web_enabled": settings.web_enabled,
        "web_host": settings.web_host,
        "web_port": settings.web_port,
        "web_access_mode": settings.web_access_mode,
        "web_public_origin": settings.web_public_origin,
        "web_username_configured": bool(settings.web_username),
        "web_password_hash_configured": bool(settings.web_password_hash),
        "web_trust_proxy_headers": settings.web_trust_proxy_headers,
        "web_session_hours": settings.web_session_hours,
        "ai_analysis_enabled": settings.ai_analysis_enabled,
        "deepseek_api_key_configured": bool(settings.deepseek_api_key),
        "deepseek_api_url": settings.deepseek_api_url,
        "deepseek_model": settings.deepseek_model,
    }


def main(argv: list[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.command == "hash-password":
        if args.stdin:
            password = sys.stdin.readline().rstrip("\r\n")
        else:
            password = getpass.getpass("请输入网页登录密码（至少16个字符）：")
            confirmation = getpass.getpass("请再次输入：")
            if password != confirmation:
                parser.error("两次输入的密码不一致")
        try:
            print(hash_password(password))
        except ValueError as exc:
            parser.error(str(exc))
        return
    load_dotenv(Path(args.env_file))
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )
    try:
        settings = Settings.from_env()
    except Exception as exc:
        parser.error(f"配置错误：{exc}")
        return
    service = _build_service(settings)

    if args.command == "init-db":
        print(f"数据库已初始化：{settings.database_path}")
        return
    if args.command == "check-config":
        output = _safe_settings(settings)
        output["mail_errors"] = settings.validate_mail()
        print(json.dumps(output, ensure_ascii=False, indent=2))
        return
    if args.command == "status":
        print(json.dumps(service.database.summary(), ensure_ascii=False, indent=2))
        return
    if args.command == "health":
        summary = service.database.summary()
        issues = settings.validate_mail()
        if int(summary.get("emails_dead", 0)) > 0:
            issues.append(f"存在{summary['emails_dead']}封邮件死信")
        output = {"healthy": not issues, "issues": issues, "summary": summary}
        print(json.dumps(output, ensure_ascii=False, indent=2))
        if issues:
            raise SystemExit(1)
        return

    now = _parse_now(getattr(args, "now", None), settings)
    try:
        if args.command == "recommend":
            outcome = _run_recorded(service, "recommend", now, service.recommend)
            print(outcome.detail)
        elif args.command == "settle":
            outcome = _run_recorded(service, "settle", now, service.settle)
            print(outcome.detail)
        elif args.command == "send-mail":
            outcome = _run_recorded(service, "send-mail", now, service.send_mail)
            print(outcome.detail)
        elif args.command == "test-mail":
            outcome = _run_recorded(service, "test-mail", now, service.test_mail)
            print(outcome.detail)
        elif args.command == "run-cycle":
            actual_now = datetime.now(settings.timezone)
            include_finalize = (
                actual_now.timetz().replace(tzinfo=None) >= settings.recommendation_deadline
            )
            outcomes, errors = _run_cycle(
                service,
                now,
                include_finalize=include_finalize,
                finalize_job_name=f"recommend-finalize:{actual_now:%Y%m%d}",
            )
            for outcome in outcomes:
                print(outcome.detail)
            if errors:
                raise SystemExit("\n".join(errors))
        elif args.command == "probe-data":
            matches = service.provider.get_matches()
            results = service.provider.get_results((now - timedelta(days=2)).date(), now.date())
            counts: dict[str, int] = {}
            for result in results.values():
                counts[result.status.value] = counts.get(result.status.value, 0) + 1
            print(
                json.dumps(
                    {
                        "matches": len(matches),
                        "complete_selling_crs_matches": sum(
                            match.betting_all_up and len(match.score_options) == 31 for match in matches
                        ),
                        "complete_selling_had_matches": sum(
                            match.had_betting_all_up and len(match.had_options) == 3 for match in matches
                        ),
                        "results": len(results),
                        "result_statuses": counts,
                    },
                    ensure_ascii=False,
                    indent=2,
                )
            )
        elif args.command == "probe-ai":
            print(json.dumps({"ok": True, "response": probe_deepseek(settings)}, ensure_ascii=False))
        elif args.command == "daemon":
            stop_event = threading.Event()
            wake_event = threading.Event()
            dashboard_server: DashboardServer | None = None

            def stop(*_):
                stop_event.set()
                wake_event.set()

            signal.signal(signal.SIGINT, stop)
            if hasattr(signal, "SIGTERM"):
                signal.signal(signal.SIGTERM, stop)
            try:
                if settings.web_enabled:
                    application = DashboardApplication(
                        settings,
                        service.database,
                        _build_manual_trigger(service, wake_event),
                    )
                    dashboard_server = DashboardServer(settings, application)
                    dashboard_server.start()
                    host, port = dashboard_server.address
                    access_note = (
                        f"由HTTPS网关保护，公开地址 {settings.web_public_origin}"
                        if settings.web_access_mode == "public"
                        else "请仅通过SSH隧道访问"
                    )
                    LOGGER.info("个人看板已监听 %s:%s（%s）", host, port, access_note)

                while not stop_event.is_set():
                    cycle_now = datetime.now(settings.timezone)
                    slot = due_recommendation_slot(
                        cycle_now,
                        settings.recommendation_times,
                        settings.recommendation_latest_start,
                        service.database.has_job_run,
                    )
                    recommend_job_name = (
                        slot_job_name(cycle_now, slot) if slot is not None else "recommend"
                    )
                    finalize_job_name = f"recommend-finalize:{cycle_now:%Y%m%d}"
                    include_finalize = (
                        cycle_now.timetz().replace(tzinfo=None) >= settings.recommendation_deadline
                        and not service.database.has_job_run(finalize_job_name)
                    )
                    _run_cycle(
                        service,
                        cycle_now,
                        include_recommend=slot is not None,
                        recommend_job_name=recommend_job_name,
                        include_finalize=include_finalize,
                        finalize_job_name=finalize_job_name,
                    )
                    if args.once:
                        break
                    wait_seconds = seconds_until_next_event(
                        datetime.now(settings.timezone),
                        settings.recommendation_times,
                        settings.recommendation_deadline,
                        settings.poll_interval_seconds,
                    )
                    wake_event.wait(wait_seconds)
                    wake_event.clear()
            finally:
                if dashboard_server is not None:
                    dashboard_server.stop()
    except KeyboardInterrupt:
        LOGGER.info("收到停止信号")
    except Exception as exc:
        LOGGER.error("%s", exc)
        raise SystemExit(1) from exc


if __name__ == "__main__":
    main(sys.argv[1:])
